// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgkmnqgihgmzlwbmknne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBna21ucWdpaGdtemx3Ym1rbm5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MDIwODIsImV4cCI6MjA3Mzk3ODA4Mn0.Qx3KCFbJPgvAMzaAEiawEb3ck_RoMERd2z__xlILhUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});